//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendMail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign
    {
        public long CampaignID { get; set; }
        public long SendMailID { get; set; }
        public string CampaignName { get; set; }
        public Nullable<System.DateTime> TimeBegin { get; set; }
        public Nullable<System.DateTime> TimeEnd { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> TimeSend { get; set; }
        public string Description { get; set; }
    
        public virtual SendMail SendMail { get; set; }
    }
}
