//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendMail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public long EmailID { get; set; }
        public Nullable<long> SendMailID { get; set; }
        public string Subject { get; set; }
        public string ContentEmail { get; set; }
        public Nullable<long> CampaignID { get; set; }
    }
}
