//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendMail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.LogSendEmails = new HashSet<LogSendEmail>();
        }
    
        public long UserID { get; set; }
        public string AccountName { get; set; }
        public string Password { get; set; }
        public System.DateTime TimeCreated { get; set; }
        public bool isAdmin { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
    
        public virtual ICollection<LogSendEmail> LogSendEmails { get; set; }
    }
}
